// src/components/FundRingWidget/FundRingWidget.svelte
<script lang="ts">
  import { onDestroy } from 'svelte'

  import { sessionStore } from '$src/stores'
  import Connected from '$components/FundRingWidget/Connected.svelte'
  import Disconnected from '$components/FundRingWidget/Disconnected.svelte'

  export let contractAddress: string = null
  export let title: string = 'Help fund us!'
  export let bodyCopy: string =
    'If you rely upon Fund Ring’s efforts to keep your project going, please consider supporting our funding goal. Every little bit helps.'

  let connected = $sessionStore.ethereumClient.getAccount().isConnected

  const unsubscribeEvents = $sessionStore.web3modal.subscribeEvents(
    newState => {
      connected = newState.name === 'ACCOUNT_CONNECTED'
    }
  )

  const unsubscribeAccount = $sessionStore.ethereumClient.watchAccount(
    newState => {
      connected = newState.isConnected
    }
  )

  onDestroy(() => {
    unsubscribeEvents()
    unsubscribeAccount()
  })
</script>

<div class="fund-ring-widget-wrapper">
  {#if connected && contractAddress}
    <Connected {contractAddress} {title} {bodyCopy} />
  {:else}
    <Disconnected {title} {bodyCopy} />
  {/if}
</div>

// src/components/web-components/fund-ring-widget.ts
import type { SvelteComponent } from 'svelte'

import WidgetSessionProvider from '$components/FundRingWidget/WidgetSessionProvider.svelte'
import css from '$components/FundRingWidget/widget.css'

customElements.define(
  'fund-ring-widget',
  class extends HTMLElement {
    _element: SvelteComponent

    constructor() {
      super()

      // Create the shadow root.
      const shadowRoot = this.attachShadow({ mode: 'open' })

      shadowRoot.innerHTML = `<style media="screen">${css}</style>`

      // Instantiate the Svelte Component
      this._element = new WidgetSessionProvider({
        // Tell it that it lives in the shadow root
        target: shadowRoot,
        // Pass any props
        props: {
          // This is the place where you do any conversion between
          // the native string attributes and the types you expect
          // in your svelte components
          contractAddress: this.getAttribute('contractAddress'),
          title: this.getAttribute('title') ?? 'Help fund us!',
          bodyCopy:
            this.getAttribute('bodyCopy') ??
            'If you rely upon Fund Ring’s efforts to keep your project going, please consider supporting our funding goal. Every little bit helps.'
        }
      })
    }
    disconnectedCallback(): void {
      // Destroy the Svelte component when this web component gets
      // disconnected. If this web component is expected to be moved
      // in the DOM, then you need to use `connectedCallback()` and
      // set it up again if necessary.
      this._element?.$destroy()
    }
  }
)
