// src/components/web-components/fund-ring-widget.ts
import type { SvelteComponent } from 'svelte'

import WidgetSessionProvider from '$components/FundRingWidget/WidgetSessionProvider.svelte'
import css from '$components/FundRingWidget/widget.css'

customElements.define(
  'fund-ring-widget',
  class extends HTMLElement {
    _element: SvelteComponent

    constructor() {
      super()

      // Create the shadow root.
      const shadowRoot = this.attachShadow({ mode: 'open' })

      shadowRoot.innerHTML = `<style media="screen">${css}</style>`

      // Instantiate the Svelte Component
      this._element = new WidgetSessionProvider({
        // Tell it that it lives in the shadow root
        target: shadowRoot,
        // Pass any props
        props: {
          // This is the place where you do any conversion between
          // the native string attributes and the types you expect
          // in your svelte components
          contractAddress: this.getAttribute('contractAddress'),
          title: this.getAttribute('title') ?? 'Help fund us!',
          description:
            this.getAttribute('description') ??
            'If you rely upon Fund Ring’s efforts to keep your project going, please consider supporting our funding goal. Every little bit helps.'
        }
      })
    }
    disconnectedCallback(): void {
      // Destroy the Svelte component when this web component gets
      // disconnected. If this web component is expected to be moved
      // in the DOM, then you need to use `connectedCallback()` and
      // set it up again if necessary.
      this._element?.$destroy()
    }
  }
)

// src/routes/filfund/components/FundRingWidget/FundRingWidget.svelte
<script lang="ts">
  import * as Filsnap from 'filsnap-adapter'
  import { onDestroy, onMount } from 'svelte'

  import Connected from '$routes/filfund/components/FundRingWidget/Connected.svelte'
  import Disconnected from '$routes/filfund/components/FundRingWidget/Disconnected.svelte'

  export let contractAddress: string = null
  export let title: string = 'Help fund us!'
  export let description: string =
    'If you rely upon Fund Ring’s efforts to keep your project going, please consider supporting our funding goal. Every little bit helps.'

  $: snapConnected = false
  $: walletConnected = false
  $: snap = null

  onMount(async () => {
    snapConnected = await Filsnap.FilsnapAdapter.isConnected()

    const mmAccounts = await window.ethereum.request({ method: 'eth_accounts' })
    walletConnected = !!(mmAccounts as string[]).length

    window.ethereum.on('accountsChanged', accounts => {
      walletConnected = !!(accounts as string[]).length
    })
  })

  onDestroy(async () => {
    window.ethereum.off('accountsChanged', accounts => {
      walletConnected = !!(accounts as string[]).length
    })
  })
</script>

<div class="fund-ring-widget-wrapper">
  {#if snapConnected && contractAddress && walletConnected}
    <Connected {contractAddress} {title} {description} bind:snap />
  {:else}
    <Disconnected
      {title}
      {description}
      bind:snap
      bind:snapConnected
      bind:walletConnected
    />
  {/if}
</div>
